--cwiczenie 1
--a)
SELECT LPAD('-', 2*(LEVEL-1), '|-') ||
       t.owner || '.' || t.type_name ||
       ' (FINAL:' || t.final ||
       ', INSTANTIABLE:' || t.instantiable ||
       ', ATTRIBUTES:' || t.attributes ||
       ', METHODS:' || t.methods || ')'
FROM all_types t
START WITH t.type_name = 'ST_GEOMETRY'
CONNECT BY PRIOR t.type_name = t.supertype_name
       AND PRIOR t.owner = t.owner;
--b) 
SELECT DISTINCT m.method_name
FROM all_type_methods m
WHERE m.type_name = 'ST_POLYGON'
  AND m.owner = 'MDSYS'
ORDER BY 1;

--c)
CREATE TABLE MYST_MAJOR_CITIES (
    FIPS_CNTRY VARCHAR2(2),
    CITY_NAME VARCHAR2(40),
    STGEOM ST_POINT
);

--d)
INSERT INTO MYST_MAJOR_CITIES (FIPS_CNTRY, CITY_NAME, STGEOM)
SELECT C.FIPS_CNTRY,
       C.CITY_NAME,
       TREAT(ST_POINT.FROM_SDO_GEOM(C.GEOM) AS ST_POINT) AS STGEOM
FROM ZTPD.MAJOR_CITIES C;

--zadanie 2
INSERT INTO MYST_MAJOR_CITIES (FIPS_CNTRY, CITY_NAME, STGEOM)
VALUES ('PL', 'Szczyrk', ST_POINT(19.036107, 49.718655, 8307));

--cwiczenie 3
--a)
CREATE TABLE MYST_COUNTRY_BOUNDARIES (
    FIPS_CNTRY VARCHAR2(2),
    CNTRY_NAME VARCHAR2(40),
    STGEOM ST_MULTIPOLYGON
);

--b) 
INSERT INTO MYST_COUNTRY_BOUNDARIES (FIPS_CNTRY, CNTRY_NAME, STGEOM)
SELECT FIPS_CNTRY,
       CNTRY_NAME,
       TREAT(ST_MULTIPOLYGON.FROM_SDO_GEOM(GEOM) AS ST_MULTIPOLYGON) AS STGEOM
FROM COUNTRY_BOUNDARIES;

--c)
SELECT B.STGEOM.ST_GEOMETRYTYPE() AS TYP_OBIEKTU,
       COUNT(*) AS ILE
FROM MYST_COUNTRY_BOUNDARIES B
GROUP BY B.STGEOM.ST_GEOMETRYTYPE()
ORDER BY B.STGEOM.ST_GEOMETRYTYPE();

--d)
SELECT B.STGEOM.ST_ISSIMPLE() 
FROM MYST_COUNTRY_BOUNDARIES B;

--zadanie 4
--a)
SELECT B.CNTRY_NAME,
       COUNT(*) AS CITY_COUNT
FROM ZTPD.MAJOR_CITIES C,
     ZTPD.COUNTRY_BOUNDARIES B
WHERE SDO_CONTAINS(B.GEOM, C.GEOM) = 'TRUE'
GROUP BY B.CNTRY_NAME
ORDER BY CITY_COUNT DESC;


--b) 
SELECT A.CNTRY_NAME AS A_NAME,
       B.CNTRY_NAME AS B_NAME
FROM ZTPD.COUNTRY_BOUNDARIES A,
     ZTPD.COUNTRY_BOUNDARIES B
WHERE B.CNTRY_NAME = 'Czech Republic'
  AND A.CNTRY_NAME <> 'Czech Republic'
  AND SDO_RELATE(A.GEOM, B.GEOM, 'mask=TOUCH') = 'TRUE';

--c) 
SELECT DISTINCT 
       B.CNTRY_NAME,
       R.NAME
FROM ZTPD.COUNTRY_BOUNDARIES B
JOIN ZTPD.RIVERS R
  ON SDO_RELATE(
        R.GEOM,
        B.GEOM,
        'mask=ANYINTERACT'
     ) = 'TRUE'
WHERE B.CNTRY_NAME = 'Czech Republic'
ORDER BY R.NAME;

--d)
SELECT
  SDO_GEOM.SDO_AREA(
    SDO_CS.TRANSFORM(
      SDO_GEOM.SDO_UNION(a.geom, b.geom, 0.005),
      2180
    ),
    0.005
  ) AS area_m2
  
FROM ZTPD.COUNTRY_BOUNDARIES a
JOIN ZTPD.COUNTRY_BOUNDARIES b
  ON 1=1
WHERE a.CNTRY_NAME = 'Czech Republic'
  AND b.CNTRY_NAME = 'Slovakia';

--e)
SELECT 
    B.GEOM AS OBIEKT,
    B.GEOM.SDO_GTYPE AS WEGRY_BEZ
FROM ZTPD.COUNTRY_BOUNDARIES B
JOIN ZTPD.WATER_BODIES W
  ON W.NAME = 'Balaton'
WHERE B.CNTRY_NAME = 'Hungary';

-- cwiczenie 5
--a)
SELECT COUNT(*) AS LICZBA_MIAST
FROM MYST_MAJOR_CITIES C, MYST_COUNTRY_BOUNDARIES B
WHERE B.CNTRY_NAME = 'Poland'
  AND SDO_WITHIN_DISTANCE(C.STGEOM, B.STGEOM, 'distance=100 unit=km') = 'TRUE';
EXPLAIN PLAN FOR
SELECT COUNT(*) AS LICZBA_MIAST
FROM MYST_MAJOR_CITIES C, MYST_COUNTRY_BOUNDARIES B
WHERE B.CNTRY_NAME = 'Poland'
  AND SDO_WITHIN_DISTANCE(C.STGEOM, B.STGEOM, 'distance=100 unit=km') = 'TRUE';

SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY);

--b) 
INSERT INTO USER_SDO_GEOM_METADATA (
    TABLE_NAME, COLUMN_NAME, DIMINFO, SRID
)
VALUES (
    'MYST_MAJOR_CITIES',
    'STGEOM',
    SDO_DIM_ARRAY(
        SDO_DIM_ELEMENT('X', -180, 180, 0.0005),
        SDO_DIM_ELEMENT('Y', -90, 90, 0.0005)
    ),
    8307
);

INSERT INTO USER_SDO_GEOM_METADATA (
    TABLE_NAME, COLUMN_NAME, DIMINFO, SRID
)
VALUES (
    'MYST_COUNTRY_BOUNDARIES',
    'STGEOM',
    SDO_DIM_ARRAY(
        SDO_DIM_ELEMENT('X', -180, 180, 0.0005),
        SDO_DIM_ELEMENT('Y', -90, 90, 0.0005)
    ),
    8307
);

--c)
CREATE INDEX MYST_MAJOR_CITIES_IDX
ON MYST_MAJOR_CITIES(STGEOM)
INDEXTYPE IS MDSYS.SPATIAL_INDEX;

CREATE INDEX MYST_COUNTRY_BOUNDARIES_IDX
ON MYST_COUNTRY_BOUNDARIES(STGEOM)
INDEXTYPE IS MDSYS.SPATIAL_INDEX;

--d) 
EXPLAIN PLAN FOR
SELECT B.CNTRY_NAME, COUNT(*) AS LICZBA_MIAST
FROM MYST_MAJOR_CITIES C, MYST_COUNTRY_BOUNDARIES B
WHERE B.CNTRY_NAME = 'Poland'
  AND SDO_WITHIN_DISTANCE(C.STGEOM, B.STGEOM, 'distance=100 unit=km') = 'TRUE'
GROUP BY B.CNTRY_NAME;

-- Wyświetlenie planu
SELECT plan_table_output
FROM TABLE(DBMS_XPLAN.DISPLAY('PLAN_TABLE', NULL, 'BASIC'));





















